feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        contract: com.example.SimpleContract
        decode404: false
        decoder: com.example.SimpleDecoder
        encoder: com.example.SimpleEncoder
        errorDecoder: com.example.SimpleErrorDecoder
        loggerLevel: ${FEIGN_CLIENT_LOGGER_LEVEL:full} #options are : none,basic,headers,full
        readTimeout: 5000
        requestInterceptors:
        # create a request interceptor for analytics
        retryer: com.example.SimpleRetryer
eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL_DEFAULT:http://localhost:8761/eureka/}
    registerWithEureka: true
  instance:
    hostname: ${EUREKA_HOST_NAME:localhost}
server:
  port: ${SERVER_PORT:0}

spring:
  profiles:
    active: dev
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/postgres-bebelink-generator}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postpass}
  application:
    name: generator-service
  jpa:
    hibernate:
      ddl-auto: ${SPRING_DATA_DDL_AUTO:create}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
