
eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL_DEFAULT:http://localhost:8761/eureka/}
    registerWithEureka: true
  instance:
    hostname: ${EUREKA_HOST_NAME:localhost}
logging:
  level:
    root: DEBUG
    org:
      springframework:
        dao: TRACE
        data: TRACE
        web: INFO
        security: WARN

server:
  port: ${SERVER_PORT:0}
spring:
  application:
    name: generator-service
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://db:5432/postgres-bebelink-generator}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postpass}
    pool:
      enabled: true
      initial-size: 20
      max-size: 100
      max-idle-time: 250m


