# Generator Service
eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL_DEFAULT:http://eureka-server:8761/eureka/}
    registerWithEureka: true
  instance:
    hostname: ${EUREKA_HOST_NAME:localhost}
    instanceId: ${eureka.instance.hostname}:${spring.application.name}:${random.value}
    prefer-ip-address: true
logging:
  level:
    root: INFO
server:
  port: ${SERVER_PORT:0}
spring:
  application:
    name: generator-service
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://generator-db:5432/postgres-bebelink-generator}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postpass}
    pool:
      enabled: true
      initial-size: 20
      max-size: 100
      max-idle-time: 250m


