app:
  webclient:
    services:
      generator:
        base-url: http://generator-service
        connect-timeout: 5000
        read-timeout: 10000
      event-queue:
        base-url: http://event-queue-service
        connect-timeout: 5000
        read-timeout: 10000

eureka:
  instance:
    hostname: ${EUREKA_HOST_NAME:localhost}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL_DEFAULT:http://localhost:8761/eureka/}
spring:

  application:
    name: router-service

server:
  port: ${SERVER_PORT:0}
