app:
  webclient:
    services:
      generator:
        base-url: http://generator-service
        connect-timeout: 5000
        read-timeout: 10000


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL_DEFAULT:http://localhost:8761/eureka/}
  instance:
    hostname: ${EUREKA_HOST_NAME:localhost}
server:
  port: ${SERVER_PORT:0}
spring:
  application:
    name: router-service
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://db:5432/postgres-bebelink-router}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postpass}
    pool:
      initial-size: 20
      max-size: 60
      max-idle-time: 30m

