eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL_DEFAULT:http://eureka-server:8761/eureka/}
  instance:
    hostname: ${EUREKA_HOST_NAME:localhost}
    instanceId: ${eureka.instance.hostname}:${spring.application.name}:${random.value}
    prefer-ip-address: true

logging:
  level:
    root: INFO
server:
  #port is set to zero to be automatically assigned by eureka
  port: ${SERVER_PORT:0}
spring:
  application:
    name: user-service
  devtools:
    restart:
      enabled: true
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://user-service-db:5432/postgres-bebelink-user-service}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postpass}
    pool:
      enabled: true
      initial-size: 6
      max-size: 24
      max-idle-time: 100m
  security:
    username: me
    password: pass
