eureka:
  instance:
    hostname: ${EUREKA_HOST_NAME:localhost}
    instanceId: ${eureka.instance.hostname}:${spring.application.name}:${random.value}
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL_DEFAULT:http://localhost:8761/eureka/}

logging:
  level:
    root: INFO
    org:
      springframework: DEBUG

server:
  #port is set to zero to be automatically assigned by eureka
  port: ${SERVER_PORT:0}
spring:
  application:
    name: users-service
  devtools:
    restart:
      enabled: true
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://db:5432/postgres-bebelink-user}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postpass}
    pool:
      enabled: true
      initial-size: 6
      max-size: 24
      max-idle-time: 100m

