eureka:
  instance:
    hostname: ${EUREKA_HOST_NAME:localhost}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL_DEFAULT:http://localhost:8761/eureka/}

server:
  #port is set to zero to be automatically assigned by eureka
  port: 0
spring:
  application:
    name: users-service
  devtools:
    restart:
      enabled: true

