eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL_DEFAULT:http://eureka-server:8761/eureka/}
  instance:
    hostname: ${EUREKA_HOST_NAME:localhost}
    instanceId: ${eureka.instance.hostname}:${spring.application.name}:${random.value}
    prefer-ip-address: true
logging:
  level:
    root: ${LOGGING_LVL_ROOT:INFO}
server:
  port: 0
spring:
  application:
    name: ${SPRING_APPLICATION_NAME:analytics-service}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    topics:
      routing-event-topic: routing-event-topic
    consumer:
      enable-auto-commit: true
      group-id: analytics-group
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring:
          json:
            trusted:
              packages: "*"
            use:
              type:
                headers: false
            value:
              default: com.seanrogandev.bebelink.analyticsservice.model.RoutingEvent